# -*- coding: utf-8 -*-
"""dashboard_peliculas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NE9lvA8i2wAdwXuR92K6qrKo1wkZYQBg
"""

!pip install firebase-admin streamlit pandas

import os

if os.path.exists("adashboard-peliculas-id-firebase-adminsdk-fbsvc-5bed941d74.json"):
    print("Archivo cargado correctamente.")
else:
    print("No se encontró el archivo.")

import pandas as pd

# Leer el archivo CSV
df = pd.read_csv("movies.csv")
df.head()  # Muestra las primeras filas

# Subir cada fila como documento a Firestore
for index, row in df.iterrows():
    doc = row.to_dict()
    db.collection("movies").add(doc)

# Leer todos los documentos de la colección "movies"
docs = db.collection("movies").stream()

# Convertir a lista de diccionarios
movies_data = [doc.to_dict() for doc in docs]

# Crear DataFrame
df_movies = pd.DataFrame(movies_data)

# Mostrar los primeros registros
df_movies.head()

import streamlit as st
import pandas as pd
import firebase_admin
from firebase_admin import credentials, firestore
# Inicializar Firebase solo una vez
if not firebase_admin._apps:
    cred = credentials.Certificate("ruta/a/tu/credentials.json")
    firebase_admin.initialize_app(cred)

db = firestore.client()

# Función para cargar datos desde Firestore
@st.cache_data
def cargar_datos():
    docs = db.collection("movies").stream()
    return pd.DataFrame([doc.to_dict() for doc in docs])

# Cargar datos
df = cargar_datos()

# Sidebar con checkbox
st.sidebar.title("Opciones")
mostrar_todo = st.sidebar.checkbox("Mostrar todos los filmes")

# Título del dashboard
st.header("🎬 Catálogo de Películas")

# Mostrar DataFrame si el checkbox está activo
if mostrar_todo:
    st.dataframe(df)
else:
    st.info("Activa el checkbox para ver todos los filmes.")

!npm install localtunnel

# Función para cargar datos desde Firestore
@st.cache_data
def cargar_datos():
    docs = db.collection("movies").stream()
    return pd.DataFrame([doc.to_dict() for doc in docs])

# Cargar datos
df = cargar_datos()

# Sidebar con checkbox
st.sidebar.title("Opciones")
mostrar_todo = st.sidebar.checkbox("Mostrar todos los filmes")

# Título del dashboard
st.header("🎬 Catálogo de Películas")

# Mostrar DataFrame si el checkbox está activo
if mostrar_todo:
    st.dataframe(df)
else:
    st.info("Activa el checkbox para ver todos los filmes.")

!npm install localtunnel

# Leer datos de la colección "movies"
def cargar_datos():
    docs = db.collection("movies").stream()
    data = [doc.to_dict() for doc in docs]
    return pd.DataFrame(data)

df = cargar_datos()

pip install streamlit

import streamlit as st

# Cargar datos
df = cargar_datos()

# Sidebar: Checkbox para mostrar todos los filmes
if st.sidebar.checkbox("Mostrar todos los filmes"):
    st.header("Todos los Filmes")
    st.dataframe(df)

st.sidebar.subheader("Buscar por título")
titulo = st.sidebar.text_input("Título contiene:")
if st.sidebar.button("Buscar"):
    resultados = df[df['title'].str.contains(titulo, case=False, na=False)]
    st.write(f"Se encontraron {len(resultados)} filmes:")
    st.dataframe(resultados)

st.sidebar.subheader("Filtrar por director")
directores = df['director'].dropna().unique()
seleccion = st.sidebar.selectbox("Selecciona un director", directores)

if st.sidebar.button("Filtrar por director"):
    filtrados = df[df['director'] == seleccion]
    st.write(f"{len(filtrados)} filmes dirigidos por {seleccion}:")
    st.dataframe(filtrados)

st.sidebar.subheader("Agregar nuevo filme")
with st.sidebar.form("formulario_filme"):
    titulo = st.text_input("Título")
    director = st.text_input("Director")
    año = st.number_input("Año", min_value=1900, max_value=2100)
    enviado = st.form_submit_button("Agregar")

    if enviado:
        nuevo = {"title": titulo, "director": director, "year": int(año)}
        db.collection("movies").add(nuevo)
        st.success("Filme agregado exitosamente")

